#define ADD_INS 1
#define DIVIDE_INS 2
#define MULTIPLY_INS 3
#define SUBTRACT_INS 4
#define LOADIMEDIATE_INS 5
#define LOADWORD_INS 6
#define STOREWORD_INS 7
#define MOVE_LOW_INS 8
#define SET_LESS_THAN_INS 9
#define XOR_IMEDIATE_INS 10
#define OR_INS 11
#define BRANCH_EQ_INS 12
#define BRANCH_NEQ_INS 13
#define SYSCALL 14

#define RETURN_REG 31
